# -- This section was auto generated by ds-pypackage --------------------------------
# -- Path setup --------------------------------------------------------------

import os
import sys

# Add the parent directory to the Python path to enable importing modules from the project
sys.path.insert(0, os.path.abspath("../../src"))

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["autoapi.extension", "sphinx.ext.githubpages"]
autoapi_dirs = ["../../src"]

# -- End of auto-generated section ------------------------------------------------
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'ds-stoa'
copyright = '2024, Grasplabs AS'
author = 'Grasplabs AS'

version = open('../../VERSION.txt').read().strip()
release = version

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration


templates_path = ['_templates']
exclude_patterns = []



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']
